name: Merge Lane
on:
  pull_request:
    types: [closed]
    branches:    
      - main
  
jobs:
  setup_npm:
    name: setup npm

    runs-on: ubuntu-latest

    if: startsWith(github.head_ref, 'components/') && github.event.pull_request.merged == true

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

  setup_bit:
      name: setup bit

      runs-on: ubuntu-latest

      needs: [setup_npm]  

      env:
        BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
        LANE_NAME: ${{ github.event.pull_request.head.ref }}

      if: startsWith(github.head_ref, 'components/') github.event.pull_request.merged == true
      
      steps:
        - uses: actions/checkout@v3
        - name: Install Bit Version Manager
          run: npm i -g @teambit/bvm
        - name: Install latest Bit version
          run: bvm install
        - name: add bvm bin folder to path
          run: echo "$HOME/bin" >> $GITHUB_PATH
        - name: Set up bit config
          run: |
            bit config set analytics_reporting false
            bit config set anonymous_reporting false
            bit config set user.token $BIT_TOKEN
        - name: Import Components
          run: bit import
        - name: Create Local Lane
          run: bit lane create $LANE_NAME
        - name: Install and Compile all Components
          run: bit install && bit compile
        - name: Merge Main Lane
          run: bit lane merge
        - name: Export the Lane
          run: bit export
  